<?php /* @var $block Strativ\DynamicProduct\Block\System\Config\Update */ ?>
<script>
require([
    'jquery',
    'prototype',
], function(jQuery){
    function syncronize() {
        params = {
        };

        new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxSyncUrl() ?>', {
            loaderArea:     true,
            asynchronous:   true,
            parameters:     params,
            onSuccess: function(transport) {
                var response = JSON.parse(transport.responseText);
            }
        });
    }

    jQuery('#update_button').click(function () {
        syncronize();
    });
});
</script>

<?php echo $block->getButtonHtml() ?>